### ISSUE TITLE
Where is jar file?

### ISSUE THREAD

**Issue by F0RIS** [OgarioProject/Ogario#1]

**Comment by ThunderGemios10** [comment]
Check https://github.com/OgarioProject/Ogar2-Server/releases

**Comment by SkorrloreGaming** [comment]
The jar file hasn't been released yet, I have been busy and I am waiting for Gemios to fix it before I do anything.

**Comment by ThunderGemios10** [comment]
@SkorrloreGaming, Fix what exactly?

**Comment by SkorrloreGaming** [comment]
You deleted my message :P, Ogar the original project has fixed the issue with connecting. I am waiting for them to push the commit and we are good 2 go.
